### ISSUE TITLE
Typo in web.xml causes ClassNotFoundException

### ISSUE THREAD

**Issue by pbroman** [kitodo/kitodo-contentserver#15]
In the web.xml file the servlet-class of GoobiContentServlet is set to `org.goobi.presentation.contentServlet.controller.GoobiContentServer`. Correct is `org.goobi.presentation.contentservlet.controller.GoobiContentServer`

**Comment by pbroman** [comment]
Pull-Request: https://github.com/kitodo/kitodo-contentserver/pull/16

**Comment by henning-gerhardt** [comment]
Closing as pull request is merged.
